"""Terrain generation for the experiments, as a `Grid`.

Same Perlin generator and the same parameters as the two source articles, but it takes
the seed explicitly and returns a plain `Grid`, so nothing is shared between runs.
"""
from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from core.grid import Grid
from perlin_numpy import generate_perlin_noise_2d


@dataclass(frozen=True)
class TerrainSpec:
    """Reproducible description of one synthetic terrain.

    The defaults are the reference configuration
    (seed 0, 100x100 grid of 10 m cells, periods (4, 4)).

    WARNING about `height_interval`: `perlin_numpy` returns values in [-1, 1], and the code
    computes `noise * (high - low) + low`. The heights therefore span
    `[low - (high - low), high]`, NOT `[low, high]`. With the reference (100, 120) the
    real range is (80, 120).
    `actual_height_range` gives the range the generator really produces.
    """

    seed: int = 0
    grid_size: tuple[int, int] = (100, 100)
    periods: tuple[int, int] = (4, 4)
    height_interval: tuple[float, float] = (100.0, 120.0)
    cell_size_m: float = 10.0

    def as_dict(self) -> dict:
        return {'seed': self.seed, 'grid_size': list(self.grid_size),
                'periods': list(self.periods),
                'height_interval': list(self.height_interval),
                'cell_size_m': self.cell_size_m}

    @property
    def actual_height_range(self) -> tuple[float, float]:
        low, high = self.height_interval
        return low - (high - low), high

    @property
    def key(self) -> str:
        return (f"s{self.seed}_g{self.grid_size[0]}x{self.grid_size[1]}"
                f"_p{self.periods[0]}x{self.periods[1]}")


def generate_terrain(spec: TerrainSpec = TerrainSpec()) -> Grid:
    """Perlin-noise terrain.

    The noise draws from a private `np.random.RandomState(seed)`: the same stream the global
    RNG gives after `np.random.seed(seed)` (so every terrain is unchanged), without touching
    the global state. Saving and restoring the global state was not enough once terrains
    are generated by several threads at once (core/parallel.py): two threads interleaved
    their draws and produced different terrains.
    """
    low, high = spec.height_interval
    noise = generate_perlin_noise_2d(spec.grid_size, spec.periods,
                                     rng=np.random.RandomState(spec.seed))
    surf = noise * (high - low) + low
    return Grid(surf=surf, cell_size_m=spec.cell_size_m)
